[alembic]
script_location = alembic
sqlalchemy.url = postgresql+pg8000://user:password@db:5432/cybercafe

# Logging configuration
file_handler_logger_name = alembic
file_handler_formatter = %%(levelname)s: %%(message)s
file_handler_args = ('alembic.log', 'a')

[post_write_hooks]
# Set to 'true' to enable the 'post_write_hooks' feature
enabled = false

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers = console
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers = console
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
formatter = generic

[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %H:%M:%S
